Add updated tokens
Workday/canvas-tokens-studio pull request #9
Opened 2023-09-13 17:29 UTC by RayRedGoose

2023-09-19 17:50 UTC, NicholasBoll commented
How many "m"s and "t"s are in the word "commit"?

2023-09-21 03:05 UTC, alanbsmith commented on tokens/sys/shape.json
> +    "xhalf": {
I'll talk to the other engineers to confirm, but I think this should be:
```suggestion
    "xHalf": {
```

2023-09-21 03:06 UTC, alanbsmith commented on tokens/sys/space.json
> +      "type": "spacing",
Question: I think we changed all our language to be `space` instead of `spacing`. Is this what we want?

2023-09-21 03:10 UTC, alanbsmith commented on tokens/sys/border.json
> +      "description": "Use to separate containers from parent backgrounds, or to separate groups of content. "
```suggestion
      "description": "Use to separate containers from parent backgrounds, or to separate groups of content."
```

2023-09-21 03:11 UTC, alanbsmith commented on tokens/sys/brand/default.json
> +        "value": "{palette.cantaloupe.400}",
Q: Why revert these back to base tokens instead of their brand token equivalents?

2023-09-21 05:23 UTC, alanbsmith requested changes
Thanks for all the updates. It looks good overall. Almost all my comments and questions are around the system colors, specifically foreground and background. Below are some detailed notes that we can discuss together.

## System Colors

General Questions:

Do you feel these state descriptors:
`default`, `hover`, `active`, `focus`, `pressed`, and `selected`

Are more helpful than a visual prominence scale? 
`subtlest`, `subtler`, `subtle`, `base` (or `default`), `bold`, `bolder`, and `boldest`

I wonder whether state descriptors belong more at the component level?

The visual prominence scale communicates how the steps relate to one another, whereas the state descriptors communicate specific intent and feel close to component-specific tokens. However, something like `color.bg.inverse.bolder` is less prescriptive than `color.bg.inverse.hover` though, and that comes with its own advantages and disadvantages. I've remapped the tokens to a prominence scale (that could probably use a few tweaks) to provide a full example and generate some discussion.

### Background

General Notes: 

- It seems like background and foreground palettes should largely mirror each other.

Specific Questions:

- What are `bg.hover`, `bg.pressed`, and `bg.selected` used for?
- `bg.translucent` might be a component token?
  - If we keep it, should it have a corresponding foreground, `fg.on-translucent`?
- Every `pressed` should have a corresponding `active` for web.
- Generally every bg / fg should have `default`, `hover`, `active`, focus`, and `pressed`.
- `inverse` should have an `active` state
  - The tertiary button makes the `bg.inverse.default` a bit weird, because it uses `bg.transparent` instead, but I think that's something we should fix at the component level instead.
  - Nit: All descriptions about "dark backgrounds" should be updated
- `primary` should have an `active` state
  - What are these used for, if Primary buttons are using brand tokens?
  - Should `primary` have a corresponding foreground, `on-primary`?
- `secondary` should have an `active` state
  - Why does `secondary` not have a `default`?
  - Should `secondary` have a corresponding foreground, `on-secondary`?
- `delete` should have an `active` state
  - Should `delete` have a corresponding foreground, `on-delete`?
- `status` colors in our status indicators have high and low emphasis and [more colors represented](https://workday.github.io/canvas-kit/?path=/docs/testing-preview-status-indicator--status-indicator-states).
  - How do these status background colors work with that system?
  - Should we have corresponding foreground colors?

### Foreground

General Notes:

- I'm not sure an `fg` section is needed at all, as they pretty well covered with `text` and `icon`, but I can see why some consolidation would be helpful.
- It seems like `fg` should generally mirror `bg`
- It seems like `text` should generally mirror `icon`.

Specific Questions:

- What are `fg.default`, `fg.secondary`, and `fg.inverse` used for?
- Interesting that `fg.inverse` doesn't follow the same pattern as `bg.inverse`
  - Might be something for us to clean up later
- What is `heading.pressed` used for?
- What is `body.pressed` used for?
- I like `on-inverse`.
- I feel like `icon` should more closely mirror `text`
- Let's get rid of `icon.hover` unless you feel strongly about keeping it

### Border

- Remove `color.border.inputs`
  - These seem like component family tokens, not system tokens
- Any state with a `pressed` should also have an `active`

## Wild Suggestions

_Take them, tweak them, or leave them._

### Background

`color.bg.default` => `color.bg.subtlest`
`color.bg.alt` => `color.bg.subtler`
`color.bg.hover` => `color.bg.subtle`
`color.bg.pressed` => `color.bg.base` (or `default`)
`color.bg.active` => remove as it's the same as `pressed`

`color.bg.inverse.default` => `color.bg.inverse.boldest`
`color.bg.inverse.hover` => `color.bg.inverse.bolder`
`color.bg.inverse.focus` => remove as it's the same as `default`
`color.bg.inverse.pressed` => `color.bg.inverse.bold`
`color.bg.inverse.active` => remove as it's the same as `pressed`

`color.bg.primary.default` => `color.bg.primary.base` (or just leave as `default`)
`color.bg.primary.hover` => `color.bg.primary.bold`
`color.bg.primary.pressed` => `color.bg.primary.bolder`
`color.bg.primary.active` => remove as it's the same as `pressed`

`color.bg.secondary.default` => `color.bg.secondary.subtlest`
`color.bg.secondary.hover` => `color.bg.secondary.bold`
`color.bg.secondary.pressed` => `color.bg.secondary.bolder`
`color.bg.secondary.active` => remove as it's the same as `pressed`

`color.bg.delete.default` => `color.bg.delete.bold`
`color.bg.delete.hover` => `color.bg.delete.bolder`
`color.bg.delete.pressed` => `color.bg.delete.boldest`
`color.bg.delete.active` => remove as it's the same as `pressed`

`color.bg.status.success.subtle` => low-emphasis success
`color.bg.status.success.bold` => high-emphasis success
`color.bg.status.alert.subtle` => low-emphasis alert
`color.bg.status.alert.bold` => high-emphasis alert
`color.bg.status.error.subtle` => low-emphasis error
`color.bg.status.error.bold` => high-emphasis error
_And add whatever other status colors you need_

### Foreground

`color.fg.default` => `color.fg.base`
`color.fg.secondary` => `color.fg.bold`

`color.fg.inverse.default` => `color.fg.inverse.boldest`

`color.fg.text.heading.default` => `color.text.heading.base` (or `default`)
`color.fg.text.heading.pressed` => `color.text.heading.bold`

`color.fg.text.body.default` => `color.text.body.base` (or `default`)
`color.fg.text.body.pressed` => `color.text.body.bold`

`color.fg.text.inverse` => `color.text.inverse.boldest`

`color.fg.text.link.default` => `color.text.link.base` (or `default`)
`color.fg.text.link.pressed` => `color.text.link.boldest`
`color.fg.text.error` => remove and use `on-status` colors instead (see below)

`color.fg.on-status.success.subtle`
`color.fg.on-status.success.bold`
`color.fg.on-status.alert.subtle`
`color.fg.on-status.alert.bold`
`color.fg.on-status.error.subtle`
`color.fg.on-status.error.bold`

`color.fg.on-inverse.default` => `color.fg.on-inverse.base` (or `default`)
`color.fg.on-inverse.hover` => `color.fg.on-inverse.bold`
`color.fg.on-inverse.pressed` => Remove as it's the same as `hover`
`color.fg.on-inverse.active` => Remove as it's the same as `hover`

`color.fg.icon.default` => `color.icon.base` (or `default`)
`color.fg.icon.hover` => `color.icon.bolder` (or just remove it)
`color.fg.icon.disabled` => `color.icon.subtle` (or maybe `disabled` is okay)
`color.fg.icon.inverse` => `color.icon.inverse.boldest`
`color.fg.icon.primary` => `color.icon.primary.base` (or `default`)

`color.border.primary` => `color.border.primary.base` (or `default` or maybe it's fine as-is)
`color.border.on-inverse.default` => `color.border.on-inverse.base` (or leave as-is)
`color.border.on-inverse.pressed` => `color.border.on-inverse.bold`
`color.border.on-inverse.active` => remove as it's the same as `pressed`
`color.border.secondary.default` => `color.border.secondary.base` (or leave as-is)
`color.border.secondary.pressed` => `color.border.secondary.bold`
`color.border.secondary.active` => remove as it's the same as `pressed`

2023-09-21 05:27 UTC, alanbsmith commented on tokens/base.json
>      "cappucino": {
Let's go ahead and fix this spelling now. ☕
```suggestion
    "cappuccino": {
```

2023-09-21 21:42 UTC, alanbsmith commented on tokens/sys/space.json
> +      "type": "spacing",
This is a tokens studio thing – disregard.

2023-09-21 21:45 UTC, alanbsmith commented on tokens/sys/brand/default.json
> +        "value": "{palette.cantaloupe.400}",
Don't reference values in the same file – resolved.

2023-10-09 20:27 UTC, alanbsmith commented on tokens/sys/space.json
> +      "description": "- Use to de-clutter your UI when alot of space is available\n- Separate banner sections from page content\n- Use to differentiate page content like page sections"
```suggestion
      "description": "- Use to declutter your UI when a lot of space is available\n- Separate banner sections from page content\n- Use to differentiate page content like page sections"
```

2023-10-09 20:28 UTC, alanbsmith commented on tokens/sys/space.json
> +      "description": "- Use sparingly\n- Helps to put focus on the primary element within your page\n- Use to de-clutter your UI when a lot of space is available"
```suggestion
      "description": "- Use sparingly\n- Helps to put focus on the primary element within your page\n- Use to declutter your UI when a lot of space is available"
```

2023-10-09 20:50 UTC, alanbsmith approved these changes

2023-10-09 20:52 UTC, merged